export const FETCH_BOOKS = "FETCH_BOOKS";
export const FILTER_THROUGH_BOOKS = "FILTER_THROUGH_BOOKS";
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const SET_FILTER_BY_GENRE = "SET_FILTER_BY_GENRE";
export const SET_FILTER_BY_YEAR = "SET_FILTER_BY_YEAR";
