const allBooks = {
  books2018: [
    {
      title: "Guns, Germs, and Steel",
      author: "Jared Diamond",
      pageCount: 440,
      dateRead: "1/2/18",
      rating: 5,
      genre: "History",
      bookType: "Paper",
      duration: 2,
      awards: null,
      id: 1,
    },
    {
      title: "How to Win Friends and Influence People",
      author: "Dale Carnegie",
      pageCount: 288,
      dateRead: "1/8/18",
      rating: 5,
      genre: "Business",
      bookType: "Pirated",
      duration: 6,
      awards: "2018 Silver Award",
      id: 2,
    },
    {
      title: "Lolita",
      author: "Vladimir Nabokov",
      pageCount: 317,
      dateRead: "1/12/18",
      rating: 4.5,
      genre: "Fiction",
      bookType: "Paper",
      duration: 4,
      awards: null,
      id: 3,
    },
    {
      title: "What Every Body Is Saying",
      author: "Joe Navarro",
      pageCount: 234,
      dateRead: "1/17/18",
      rating: 4.5,
      genre: "Business",
      bookType: "Paper",
      duration: 5,
      awards: null,
      id: 4,
    },
  ],
  books2019: [
    {
      title: "A Glorious Defeat",
      author: "Timothy Henderson",
      pageCount: 216,
      dateRead: "3/4/19",
      rating: 5,
      genre: "Latin America",
      bookType: "Paper",
      duration: 62,
      awards: null,
      id: 5,
    },
    {
      title: "The General In His Labyrinth",
      author: "Gabriel Garcia Marquez",
      pageCount: 285,
      dateRead: "3/7/19",
      rating: 3.5,
      genre: "Latin America",
      bookType: "Paper",
      duration: 3,
      awards: null,
      id: 6,
    },
    {
      title: "Guerrilla Warfare",
      author: "Che Guevara",
      pageCount: 157,
      dateRead: "3/27/19",
      rating: 4.5,
      genre: "Latin America",
      bookType: "Paper",
      duration: 20,
      awards: null,
      id: 7,
    },
  ],
  books2020: [
    {
      title: "The Rich and the Rest of Us",
      // Eventually this will need to be an array and capable of handling either.
      author: "Tavis Smiley",
      pageCount: 222,
      dateRead: "2/5/20",
      rating: 3,
      genre: "Theory",
      bookType: "Paper",
      duration: 39,
      awards: null,
      id: 8,
    },
    {
      title: "Where We Go From Here",
      author: "Bernie Sanders",
      pageCount: 270,
      dateRead: "2/23/20",
      rating: 4,
      genre: "Memoir",
      bookType: "Paper",
      duration: 18,
      awards: null,
      id: 9,
    },
    {
      title: "Station Eleven",
      author: "Emily St. John Mandel",
      pageCount: 333,
      dateRead: "3/5/20",
      rating: 5,
      genre: "Fiction",
      bookType: "Borrowed",
      duration: 11,
      awards: null,
      id: 10,
    },
  ],
  books2021: [
    {
      title: "The Power and the Glory",
      author: "Graham Greene",
      pageCount: 222,
      dateRead: "1/5/21",
      rating: 5,
      genre: "Fiction",
      bookType: "Paper",
      duration: 5,
      awards: null,
      id: 11,
    },
    {
      title: "Empire",
      author: "Stephen Howe",
      pageCount: 168,
      dateRead: "1/7/21",
      rating: 4,
      genre: "Theory",
      bookType: "Pirated",
      duration: 2,
      awards: null,
      id: 12,
    },
    {
      title: "How To Watch TV News",
      author: "Neil Postman",
      pageCount: 192,
      dateRead: "1/19/21",
      rating: 5,
      genre: "Theory",
      bookType: "Audio",
      duration: 12,
      awards: null,
      id: 13,
    },
  ],
  books2022: [
    {
      title: "Remina",
      // Eventually this will need to be an array and capable of handling either.
      author: "Junji Ito",
      pageCount: 250,
      dateRead: "1/5/22",
      rating: 3.5,
      genre: "Horror",
      bookType: "Paper",
      duration: 8,
      awards: null,
      id: 14,
    },
    {
      title: "The Money Game",
      author: "Adam Smith",
      pageCount: 272,
      dateRead: "1/8/22",
      rating: 5,
      genre: "Business",
      bookType: "Pirated",
      duration: 3,
      awards: null,
      id: 15,
    },
    {
      title: "The Communist Manifesto",
      // @TODO: Needs to be an array
      author: "Karl Marx, Friedrich Engels",
      pageCount: 160,
      dateRead: "1/15/22",
      rating: 5,
      genre: "Theory",
      bookType: "Paper",
      duration: 7,
      awards: null,
      id: 16,
    },
  ],
};

export default allBooks;
